### ISSUE TITLE
event listener register

### ISSUE THREAD

**Issue by gaggala** [plusnew/core#2]
When the value for e.g. onclick attribute is undefined, the framework throws a non-descriptive exception.

**Comment by Hardenberg** [comment]
Do u have steps to reproduce? or some snippets?

**Comment by gaggala** [comment]
`<span onclick={undefined} />`

This obviously should be an compiler error, but also it should have a meaningful exception if no typescript is used

**Comment by plusgut** [comment]
is fixed in https://github.com/plusnew/driver-dom
