### ISSUE TITLE
not compatible with Typescript 4.8.4

### ISSUE THREAD

**Issue by Reloaded2** [plusnew/core#420]
### Expected behavior and actual behavior.
When I use Plusnew with the latest Typescript version 4.8.4, the Typescript compiler shows the following error message:
`node_modules/@plusnew/state/src/util/forEach.ts:8:7 - error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'T[keyof T]'.`

**Comment by plusgut** [comment]
fixed in f2fea69e2f4febc0073cd886f3f43c99e1c45791
