### ISSUE TITLE
<input type="number"> with decimal values doesn works

### ISSUE THREAD

**Issue by Reloaded2** [plusnew/core#424]
### Expected behavior and actual behavior.

For example, I as a user would like to enter "30,5" in an input number field . When I type "30," the input number simply remains empty.

### Steps to reproduce the problem.
```
 {
            plusnew.createElement(
		        "input" as any,
		        {
		          type: "number",
		          value: "30,",
		        },
		        null,
		        null,
		      )
  }


### Specifications like the version of the project or browser version
"plusnew": "1.7.9",

**Comment by plusgut** [comment]
thanks for the report, https://github.com/plusnew/driver-dom/commit/c6f1c1fc73ee792a0df33ee3cdbf3ce99b9e27d7 this should fix it and is released with v1.5.2
